### PR TITLE
Update getID3 to version 1.9.19-201912131005

### LINKED ISSUE #369: getid3 PHP 7.4 warnings
The current bundled version of getid3 is not fully compatible with PHP 7.4 . [Latests versions 1.9.18 and 1.9.19](https://github.com/JamesHeinrich/getID3/releases) contain the necessary fixes.

Warning output:
```
PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in ../s3-uploads/lib/getid3/getid3.php on line 554
PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in ../s3-uploads/lib/getid3/getid3.php on line 555
```

### PR DESCRIPTION
**Pull request by luishdz1010**
Fixes 7.4 PHP incompatibilities

Fixes #369

### CODE REVIEW

**Comment by AdrienPoupa** [comment]
Why not use composer for this?

**Comment by luishdz1010** [comment]
> Why not use composer for this?

See https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php#L47-L54 for the reasoning.

It seems that Core finally updated the getID3 library to a more recent version (1.19.18). Perhaps we don't need to include our own copy anymore?

**Comment by AdrienPoupa** [comment]
I'm not questioning the reasoning behind not using WordPress' but they could include the lib with composer instead of versioning it

**Comment by joehoyle** [comment]
good points to both @luishdz1010 and @AdrienPoupa.

- [ ] Confirm if we still need this newer version, or did WordPress update?
- [ ] Pull this in via composer if it's still needed.

**Comment by austinpray** [comment]
@joehoyle vendoring/bringing this in with composer is not needed anymore. 1.9.18 (included in core) fixes the original reason why vendoring was required.

1.9.19 fixes some linting issues: but that would not be a concern if this was brought in with composer anyway. 

I would tag a breaking change that
- requires a recent version of WordPress
- removes vendored getid3

**Comment by tillkruss** [comment]
@joehoyle: Here is the core changeset: https://core.trac.wordpress.org/changeset/46112

**Comment by joehoyle** [comment]
Closed in favor of #391, thanks for the investigation and work @luishdz1010 @tillkruss  @austinpray @AdrienPoupa

**Pull request closed without merging**
