### PR TITLE
Added `get_s3_path` function instead of hard coding s3 path.

### PR DESCRIPTION
**Pull request by johnrom**
I had use this functionality elsewhere and thought it should be part of the public API.

### CODE REVIEW

**Review by joehoyle — APPROVED** [review]

**Comment by joehoyle** [comment]
Thanks

**Comment by johnrom** [comment]
It looks like the latest releases didn't include this PR or #582.

**Comment by joehoyle** [comment]
@johnrom I released 3.0.7 with this https://github.com/humanmade/S3-Uploads/releases/tag/3.0.7

**Comment by johnrom** [comment]
Thanks!

**Pull request merged**
