### PR TITLE
Remove misleading documentation from README.md

### PR DESCRIPTION
**Pull request by jezemery**
Documentation in README.md suggests you can create an IAM user using the `create-iam-user ` subcommand, however this subcommand does not actually exist.

### CODE REVIEW

**Comment by rmccue** [comment]
Huh, this was removed in  9a188e4784903941cac358491a18a7864030656c. @joehoyle was that intentional?

**Comment by jezemery** [comment]
> Huh, this was removed in [9a188e4](https://github.com/humanmade/S3-Uploads/commit/9a188e4784903941cac358491a18a7864030656c). @joehoyle was that intentional?

I would say, it's a very useful command to have. So if there's work required to reinstate it, I'm happy to take a look.

**Comment by joehoyle** [comment]
This was removed intentionally, mostly because it's something we never used, so it became out of date and untested. @jezemery if you wanted to PR and test it, I think we could bring it back.

**Comment by jezemery** [comment]
I'll take a look and see what I can do

**Comment by joehoyle** [comment]
In the meantime, we can merge this

**Review by joehoyle — APPROVED** [review]

**Pull request merged**
