### PR TITLE
213: Fix Travis CI builds and use wp-phpunit/wp-phpunit to run phpunit tests

### LINKED ISSUE #213: Update Travis CI config
CI is failing due to configuration problems.

### PR DESCRIPTION
**Pull request by Nikschavan**
Fixes #213

### CODE REVIEW

**Comment by joehoyle** [comment]
Hey @Nikschavan thanks for this! As it happens I've also put some work into the tests, to get a single docker image to run it all instead, so we can more easily run it locally and the like. That isn't quite ready, so I tihnk there would be benefit to merging this if it's already working, but I see the build is still failing here.

**Comment by Nikschavan** [comment]
This PR is still WIP, I will change this to draft until then.

Currently, only one of the [tests seems to be failing](https://travis-ci.com/github/humanmade/S3-Uploads/builds/162635859#L353) as to previously Travis was not starting test due to different configuration errors. 

The failing test is `Test_S3_Uploads::test_generate_attachment_metadata_for_pdf` which seems to be added in to https://github.com/humanmade/S3-Uploads/issues/143

I am still debugging this test right now. It appears the function `wp_get_image_editor()` is returning `WP_Error` when testing for the thumbnail generation for the PDF files. If you have any ideas on this do let me know.

**Comment by joehoyle** [comment]
Hmm that might be because imamagick is not set up to handle PDF images. I had to do work in my branch to fix it. I'll push up my unit test changes to another PR so we can compare approaches.

**Comment by joehoyle** [comment]
@Nikschavan I've pushed my approach up in https://github.com/humanmade/S3-Uploads/pull/402, which uses a self-contained docker image as the test environment. That will also install imagick and have the PDF extensions

**Comment by Nikschavan** [comment]
The approach in #402 sounds nice as it also does not require uploading to an actual s3 bucket during tests.

Do you think it's worth the effort to continue working on #400? I am happy to close this PR in favor of #402.

**Comment by joehoyle** [comment]
@Nikschavan ok cool. Yes, I thikn that will prove to be the better aproach. Are you ok to tinker with docker too? I think it would be great to switch to wp-phpunit away from SVN in the docker image buidling. Also, if you wanted to have a bash at setting up travis to run the image that would be great. I've been using this command to run tests:

`docker run --rm -v $PWD/../../:/code -it s3-uploads-unit-tests`.

We can build the image and upload it to dockerhub too, so maybe the image will be more like `humanmade/s3-uploads-unit-tests`.

I think we _could_ also split the dockerfile into 2 images: one that is a wordpress-unit-testing ready to go image, then inherit from that file/image in an s3-uploads specific image which just adds minio etc to it.

**Comment by Nikschavan** [comment]
Sure, I will work on #402 to move that one forward and close #400.

**Pull request closed without merging**
