### PR TITLE
Improved S3 autoloader performance.

### PR DESCRIPTION
**Pull request by igmoweb**
`s3_uploads_autoload()` was checking if a file exists for any class name passed to it. That was hurting performance in every page load.
The fix tries to recognize if the class is a S3_Uploads family

### CODE REVIEW

**Comment by igmoweb** [comment]
Just another comment I'm curious about. The way `s3_uploads_autoload` loads a class does not match with some classes naming. For instance `S3_Uploads_ChangedFilesIterator` will be parsed to a filename `class-s3-uploads-changedfilesiterator.php` which does not actually exist so it's not this autoloader the one that is loading it. Is it being loaded from another place?

**Comment by joehoyle** [comment]
The idea of this makes sense to me, @rmccue any thoughts?

**Comment by rmccue** [comment]
Seems legit to me. In a modern-standards-world, we'd probably have everything under the `S3_Uploads` namespace instead, which would be a bit of a nicer check.

No idea on the ChangedFilesIterator though; @joehoyle?

**Comment by archon810** [comment]
This is 3 years old and still not merged?

**Comment by vijayant123** [comment]
Does this issue still exist in latest release (version 2.2.1)?

**Comment by joehoyle** [comment]
We now use the "native" composer classmate autoloader, so this is no longer needed. Sorry for how long this sat around for everyone!

**Pull request closed without merging**
