### PR TITLE
Update to AWS SDK 3.0

### PR DESCRIPTION
**Pull request by joehoyle**

### CODE REVIEW

**Comment by fklein-lu** [comment]
@joehoyle It seems that the current version of the SDK in the plugin is 2.8.10. Is this PR still valid?

**Comment by spacedmonkey** [comment]
The latest version of V2 of SDK is 2.8.23. The latest stable is 3.10.1. Either way this is out of date.

**Comment by joehoyle** [comment]
Phew, finally got all the tests passing and switched to the latest version. @sanchothefat cc

**Comment by sanchothefat** [comment]
@joehoyle you beauty, thanks!

**Pull request merged**
