### PR TITLE
Fix upload-directory command

### PR DESCRIPTION
**Pull request by iamlili**
- was using incorrect namespace
- this fixes https://github.com/humanmade/S3-Uploads/issues/513

### CODE REVIEW

**Comment by joehoyle** [comment]
Hmm wondering how this didn't get caught by the static analysis via psalm.

**Comment by joehoyle** [comment]
Ah IIRC this is to do with the WP CLI stubs not being available so the WP CLI command does not get type checking.

**Review by joehoyle — APPROVED** [review]

**Comment by joehoyle** [comment]
@iamlili thanks!

**Comment by iamlili** [comment]
@joehoyle no probs!

**Pull request merged**
