### PR TITLE
Fix installation procedure

### PR DESCRIPTION
**Pull request by tristanbes**
when typing `S3-Uploads` it says no plugin found.
when typing `s3-uploads` it correctly activates the plugin

### CODE REVIEW

**Comment by rmccue** [comment]
Thanks for your PR!

The name here needs to match whatever the directory name for the plugin is. As this repo is called `S3-Uploads`, most people will clone it down with that name, so the instructions here are already correct as far as I can see. They are also only indicative, as it's just telling you how to activate a plugin.

I'm going to close this for now, but feel free to comment if you think we can solve this better.

**Comment by tristanbes** [comment]
Well `composer req humanmade/s3-uploads` clones as `s3-uploads`

Maybe add an alternative line something like: 

If you downloaded the plugin with composer, run `wp plugin activate s3-uploads`

Even if it's just information, nothing is more irritative than copy/paste commands that doesn't work.

**Comment by tristanbes** [comment]
And also @rmccue  please consider releasing a new version via github tags, you got users that use your plugin with composer that is stuck with a very old version, not all of them download via wordpress. See: https://github.com/humanmade/S3-Uploads/issues/283

**Comment by rmccue** [comment]
Our priority for our code is always our internal projects and engineers. We make these projects available as open source as a way of giving back to the community (which also helps us out with contributions), but we can't support things we're not using without doing work for free. :)

**Comment by tristanbes** [comment]
See this with another eye: tagging releases with github respecting the `SemVer` constraint has nothing to do with composer. :-)

It's just a good practice when you do something open source.

**Comment by rmccue** [comment]
Sure, which is why we'll get to it eventually, but internally we use submodules tied to commits, so tags are mostly irrelevant. :)

**Pull request closed without merging**
